$schema: https://raw.githubusercontent.com/cardinalby/xgo-pack/master/config_schema/config.schema.v1.json
dist_dir: dist
tmp_dir: dist/tmp
src:
  main_pkg: cmd/drt
  icon: xgo-pack:default-icon # Set path to your icon
targets:
  common:
    product_name: drTags
    version: 1.0.0
    identifier: com.github.abakum.drt
    copyright: © 2025, com.github.abakum
    high_dpi: false
    bin_name: drt
  windows:
    amd64:
      out_dir: windows_amd64
      build_bin: false # Build and keep binary
  macos:
    common:
      codesign:
        sign: true
      bundle:
        bundle_name: drt.app
        hide_in_dock: false
      dmg:
        dmg_name: drt.dmg
    arm64:
      out_dir: darwin_arm64
      build_bin: false # Build and keep binary
      build_bundle: false # Build and keep app bundle
      build_dmg: false # Build and keep dmg image with bundle
    amd64:
      out_dir: darwin_amd64
      build_bin: false # Build and keep binary
      build_bundle: false # Build and keep app bundle
      build_dmg: false # Build and keep dmg image with bundle
  linux:
    common:
      deb:
        deb_name: drt.deb
        name: drt
        section: default
        maintainer: com.github.abakum
        dst_bin_path: /usr/bin/drt
        desktop_entry:
          add_desktop_entry: true
          add_icon: true
          dst_icon_path: /usr/share/icons/com.github.abakum.drt.png
          name: drt
          type: Application
          terminal: true
          no_display: false
    arm64:
      out_dir: linux_arm64
      build_bin: false # Build and keep binary
      build_deb: false # Build and keep deb package
    amd64:
      out_dir: linux_amd64
      build_bin: true # Build and keep binary
      build_deb: true # Build and keep deb package
